Internet-I-main/uyg05-IdentityApp/Controllers/FileManageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using System.Diagnostics;
using System.Data;
using System.IO;
using uyg05_IdentityApp.Models;
using uyg05_IdentityApp.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace uyg05_IdentityApp.Controllers
{
    public class FileManageController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly AppDbContext _context;
        private readonly IFileProvider _fileProvider;

        public FileManageController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager, SignInManager<AppUser> signInManager, AppDbContext appDbcontext, IFileProvider fileProvider, AppDbContext context)
        {
            _context = appDbcontext;
            _roleManager = roleManager;
            _fileProvider = fileProvider;
            _userManager = userManager;
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var fileManageModel = _context.FileManagers.Select(x => new FileManageModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Link = x.Link,
                CategoryName = x.Category.Name,

            }).ToList();
            return View(fileManageModel);
        }

        public IActionResult Insert()
        {
            List<SelectListItem> kategoriname = (from x in _context.Categories.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.Name,
                                                     Value = x.CategoryId.ToString()
                                                 }).ToList();
            ViewBag.kategoriname = kategoriname;
            return View();
        }

        [HttpPost]
        public IActionResult Insert(FileManageModel model)
        {
            var rootfolder = _fileProvider.GetDirectoryContents("wwwroot");
            var fileUrl = "-";
            if (model.File.Length > 0 && model.File != null)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(model.File.FileName);
                var dosyayolu = Path.Combine(rootfolder.First(x => x.Name == "Files").PhysicalPath, fileName);
                using var stream = new FileStream(dosyayolu, FileMode.Create);
                model.File.CopyTo(stream);
                fileUrl = fileName;
            }
            else
            {
                Console.WriteLine("Dosya seçilmedi veya link boş.");
            }



            var fileManage = new FileManage();
            fileManage.Name = model.Name;
            fileManage.Description = model.Description;
            fileManage.Link = fileUrl;
            fileManage.CategoryId = model.CategoryId;
            _context.FileManagers.Add(fileManage);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {

            var fileModel = _context.FileManagers.Select(x => new FileManageModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Link = x.Link,

            }).SingleOrDefault(x => x.Id == id);
            return View(fileModel);
        }

        [HttpPost]
        public IActionResult Edit(FileManageModel model)
        {
            var filemanage = _context.FileManagers.SingleOrDefault(x => x.Id == model.Id);
            filemanage.Name = model.Name;
            filemanage.Description = model.Description;
            filemanage.Link = model.Link;


            _context.FileManagers.Update(filemanage);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var fileManageModel = _context.FileManagers.Select(x => new FileManageModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Link = x.Link,
                CategoryId = x.CategoryId,
                CategoryName = x.Category.Name,

            }).SingleOrDefault(x => x.Id == id);
            return View(fileManageModel);
        }

        [HttpPost]
        public IActionResult Delete(FileManageModel model)
        {
            var filemanage = _context.FileManagers.SingleOrDefault(x => x.Id == model.Id);
            _context.FileManagers.Remove(filemanage);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Detail(int id)
        {
            var fileModel = _context.FileManagers.Select(x => new FileManageModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Link = x.Link,
                CategoryId = x.CategoryId,
                CategoryName = x.Category.Name,

            }).SingleOrDefault(x => x.Id == id);
            return View(fileModel);

        }
        public IActionResult Users()
        {
            return View();
        }

        [Authorize]

        public IActionResult IndexForUser()
        {
            var filesModel = _context.FileManagers.Select(x => new FileManageModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Link = x.Link,
                CategoryId = x.CategoryId,
                CategoryName = x.Category.Name,

            }).ToList();
            return View(filesModel);
        }

        public IActionResult DisplayForUser(int id)
        {
            var fileModel = _context.FileManagers.Select(x => new FileManageModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Link = x.Link,
                CategoryId = x.CategoryId,
                CategoryName = x.Category.Name,

            }).SingleOrDefault(x => x.Id == id);
            return View(fileModel);

        }
        public IActionResult GetCategoryList()
        {
            var category = _context.Categories.ToList();
            return View(category);
        }

        public IActionResult CategoryAdd()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CategoryAdd(Category model)
        {
            var categoryExists = _context.Categories.FirstOrDefault(c => c.Name == model.Name);
            if (categoryExists == null)
            {
                var newCategory = new Category();
                newCategory.Name = model.Name;
                _context.Categories.Add(newCategory);
                _context.SaveChanges();
            }

            return RedirectToAction("GetCategoryList");
        }

    }
}

Internet-I-main/uyg05-IdentityApp/Controllers/UserListController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using uyg05_IdentityApp.Models;
using uyg05_IdentityApp.ViewModels;

namespace egitim_portali_projesi.Controllers
{
    public class UserListController : Controller
    {
        private readonly AppDbContext _context;

        public UserListController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult UsersList()
        {
            return View();
        }

        public IActionResult UserListAjax()
        {
            var userlistModels = _context.Users.Select(x => new UserModel()
            {
                Id = x.Id,
                FullName = x.FullName,
                Email = x.Email,
                UserName = x.UserName,

            }).ToList();


            return Json(userlistModels);
        }
        public IActionResult UserListByIdAjax(string id)
        {
            var userlistModel = _context.Users.Where(s => s.Id == id).Select(x => new AppUser()
            {
                Id = x.Id,
                FullName = x.FullName,
                UserName = x.UserName,
                Email = x.Email,

            }).SingleOrDefault();

            return Json(userlistModel);
        }

    }
}

Internet-I-main/uyg05-IdentityApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dosya Yönetimi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/uyg05_IdentityApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dosya Yönetimi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <partial name="_MenuPartial"></partial>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Dosya Yönetim Portalı - Ali Kahraman - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Internet-I-main/uyg05-IdentityApp/Views/Shared/_LayoutAdminLTE.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin Paneli</title>

    <!-- Custom fonts for this template-->
    <link href="~/AdminLTE/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"></link>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/AdminLTE/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Admin" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin Paneli <sup></sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Dosya Yönetim İşlemleri
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>İşlemler</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="FileManage" asp-action="Index">Dosyaları Düzenle</a>
                        <a class="collapse-item" asp-controller="FileManage" asp-action="GetCategoryList" >Dosya Türleri</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Kullanıcı İşlemleri</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="UserList"asp-action="UsersList">Kullanıcıları Görüntüle</a>
                        <a class="collapse-item" asp-controller="Home" asp-action="GetRoleList">Rolleri Görüntüle</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Diğer İşlemler
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Diğer İşlemler</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Diğer İşlemler:</h6>
                        <a class="collapse-item" asp-controller="Home" asp-action="Register">Kayıt Ol</a>
                        <a class="collapse-item" asp-controller="Home" asp-action="Index">Anasayfaya Dön</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="~/AdminLTE/img/undraw_rocket.svg" alt="...">
                <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
                <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - Alerts -->

                            <!-- Dropdown - Alerts -->

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"> @User.Identity.Name</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-controller="Home" asp-action="UserPage">
                                    <i class="fa fa-user-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Logout">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Oturumu Kapat
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->

                    <!-- Content Row -->
                    <div class="row">


                    </div>

                    <!-- Content Row -->
                    <div class="row">

                        <!-- Content Column -->
                        <div class="col-lg-6 mb-4">

                            <!-- Project Card Example -->


                        <div class="col-lg-6 mb-4">

 
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    @RenderBody()

    <!-- Bootstrap core JavaScript-->
    <script src="~/AdminLTE/vendor/jquery/jquery.min.js"> </script>
    <script src="~/AdminLTE/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/AdminLTE/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/AdminLTE/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/AdminLTE/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/AdminLTE/js/demo/chart-area-demo.js"></script>

    <script src="~/AdminLTE/js/demo/chart-pie-demo.js"></script>

</body>

</html>

Internet-I-main/uyg05-IdentityApp/Views/Shared/_MenuPartial.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
    </li>

   @if (User.Identity.IsAuthenticated)
   {
        if (User.IsInRole("Admin"))
        {
            <li>
                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Paneli</a>
            </li>
        }
        <li>
            <a class="nav-link text-darkS" asp-area="" asp-controller="FileManage" asp-action="IndexForUser" style="color: red; font-weight: bold;" >DOSYALAR</a>
        </li>
   }

   



</ul>